In [3]:
import numpy as np
import pandas as pd
import sklearn 
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA

In [4]:
def one_hot(original_dataframe, feature_to_encode):
    dtype = original_dataframe[feature_to_encode].dtype
    
    if dtype == 'object':
        dummies = pd.get_dummies(original_dataframe[[feature_to_encode]])
        res = pd.concat([original_dataframe, dummies], axis=1)
        res = res.drop([feature_to_encode], axis=1)
        
        return(res) 
    else: 
        return original_dataframe

def process_data(data_path):
    import numpy as np
    import pandas as pd
    import sklearn 
    from matplotlib import pyplot as plt
    from sklearn.decomposition import PCA
    
    data = pd.read_csv(data_path)

    for i, col in enumerate(data.columns):
        data = one_hot(data, col)
        
    data = data.to_numpy()
    data = np.nan_to_num(data)
    
    return data

In [87]:
train = pd.read_csv('./data/train.csv')

In [88]:
def one_hot(original_dataframe, feature_to_encode):
    dtype = original_dataframe[feature_to_encode].dtype
    
    if dtype == 'object':
        dummies = pd.get_dummies(original_dataframe[[feature_to_encode]])
        res = pd.concat([original_dataframe, dummies], axis=1)
        res = res.drop([feature_to_encode], axis=1)
        
        return(res) 
    else: 
        return original_dataframe

In [89]:
data = train

for i, col in enumerate(train.columns):
    data = one_hot(data, col)

In [90]:
data = data.to_numpy()
data = np.nan_to_num(data)

In [92]:
pca = PCA(n_components=100)
pca.fit(data)
data_t = pca.transform(data)

In [93]:
print(data_t)

[[ 2.74936940e+04 -2.99390195e+03 -2.91099509e+02 ... -4.03106289e-02
   3.31353963e-02  4.46830293e-02]
 [ 5.47887375e+02 -9.29979749e+02  7.46484713e+02 ...  2.57237581e-01
   2.38535365e-01 -1.59697638e-02]
 [ 4.25796112e+04 -7.01908375e+02 -4.72423087e+02 ...  6.04102842e-02
   1.45982451e-01 -1.64704880e-01]
 ...
 [ 8.54831706e+04 -4.35077300e+03 -1.00386691e+03 ...  4.67500200e-01
   3.08211731e-01 -1.37559603e-01]
 [-3.88047772e+04  5.06480383e+02  2.84327142e+02 ... -1.39437191e-01
  -2.53145054e-01 -1.96836371e-01]
 [-3.34214006e+04  5.50709745e+02  7.01748178e+02 ...  1.42406976e-01
   8.30597320e-02  5.58182775e-02]]


In [5]:
data_t = process_data('./data/train.csv')

In [6]:
print(data_t)

[[1.000e+00 6.000e+01 6.500e+01 ... 0.000e+00 1.000e+00 0.000e+00]
 [2.000e+00 2.000e+01 8.000e+01 ... 0.000e+00 1.000e+00 0.000e+00]
 [3.000e+00 6.000e+01 6.800e+01 ... 0.000e+00 1.000e+00 0.000e+00]
 ...
 [1.458e+03 7.000e+01 6.600e+01 ... 0.000e+00 1.000e+00 0.000e+00]
 [1.459e+03 2.000e+01 6.800e+01 ... 0.000e+00 1.000e+00 0.000e+00]
 [1.460e+03 2.000e+01 7.500e+01 ... 0.000e+00 1.000e+00 0.000e+00]]
